name: Update GitHub Actions Dependencies

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:      # Manual trigger option

jobs:
  update-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # Required to modify repository contents
      pull-requests: write    # Required to create PRs
      actions: read           # Required to read workflow files

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Update GitHub Actions
        uses: ThreatFlux/githubWorkFlowChecker@b85ebeb97aebf83af4773d96738922a065a77037  # v1.20250408.1
        with:
          owner: ${{ github.repository_owner }}
          repo-name: ${{ github.event.repository.name }}
          labels: "dependencies,security"
          token: ${{ secrets.GIT_TOKEN }}
