name: Version Auto-increment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'pyproject.toml'
      - 'setup.py'
      - '.github/workflows/**'
      - '**.md'

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55  # v5.5.0
      with:
        python-version: '3.13'

    - name: Get current version
      id: current_version
      run: |
        # Check if make is available
        if ! command -v make &> /dev/null
        then
            echo "Make could not be found, installing..."
            sudo apt-get update
            sudo apt-get install make
        fi
        # Use Makefile to get the current version
        echo "Getting current version information..."
        make get-version
        
        # Extract version from __init__.py (same as Makefile does)
        VERSION=$(cat src/yaraflux_mcp_server/__init__.py | grep __version__ | sed -e "s/__version__ = \"\(.*\)\"/\1/")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Calculate new version using the same logic as Makefile
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        PATCH=$(echo $VERSION | cut -d. -f3)
        NEW_PATCH=$(expr $PATCH + 1)
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Bump version
      run: |
        echo "Bumping version from ${{ steps.current_version.outputs.version }} to ${{ steps.current_version.outputs.new_version }}..."
        make bump-version
        
        # Verify the version was updated correctly
        echo "Verifying version update..."
        make get-version

    - name: Create version bump commit
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pyproject.toml setup.py Dockerfile src/yaraflux_mcp_server/__init__.py
        git commit -m "chore: bump version to ${{ steps.current_version.outputs.new_version }}"
        git tag -a "v${{ steps.current_version.outputs.new_version }}" -m "Version ${{ steps.current_version.outputs.new_version }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true

    outputs:
      new_version: ${{ steps.current_version.outputs.new_version }}